sudo: false
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run test:travis